import '../styles/globals.css'
import { Metadata } from "next";
import {  Roboto } from "next/font/google";

const font = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});
export const metadata = {
  title: "Maglo",
  description: "Generated by create next app",
};
export default function App({ Component, pageProps }) {
  return (
  <main className={font.className}>
    <Component {...pageProps}/>
    </main> 
    )
}
