import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
    <title>Maglo</title>
    <meta name="Maglo" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico?v=2" />
  </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
